### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by davidperezgar** [Longoon12000/Virtual-Hosts#1]
Hello, 
I'm using Mac and Firefox Dev Edition, and is not working. I set up IP and hostname and is not working. 

Something else to do? Thanks

**Comment by serhumanos** [comment]
Same here, on Linux KDE Neon (Ubuntu Based) Firefox 98.0.1

**Comment by digitalnomad91** [comment]
Likewise. Looks like dev abandoned project. I may try to put together a new one when I get some time.

Edit: Nevermind, found this one that works great: https://addons.mozilla.org/en-US/firefox/addon/livehosts/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

**Comment by RainOrigami** [comment]
Hi guys

This addon works, I use it myself constantly.

If you want help, it's not useful to say "it doesn't work". Provide details, exact steps what you do, what you expect and what is actually happening.

Here is a video of it working:

https://user-images.githubusercontent.com/51454971/201520604-cc3712a5-22d2-45d3-b1c5-c45c3ac5cb69.mp4

The project is not abandoned, there hasn't been any updates because it works.

**Comment by serhumanos** [comment]
Hi, I like the purpose of this Addon, so my intention is help to this Addon work the well it can.

For me, In some case I get a blank page (with 404 not found favicon).. in other cases, it show this message: 
```
Misdirected Request

The client needs a new connection for this request as the requested host name does not match the Server Name Indication (SNI) in use for this connection.
```
I tryed with the servers that you used in your example and it worked, but if you try with "www.google.com" --> "www.bing.com" it fails

**Comment by RainOrigami** [comment]
> but if you try with "www.google.com" --> "www.bing.com" it fails

that is not supposed to work. this addon rewrites the Host HTTP header. I have no clue what you are trying to accomplish, but rewriting google to bing makes no sense.

**Comment by serhumanos** [comment]
> > but if you try with "www.google.com" --> "www.bing.com" it fails
> 
> that is not supposed to work. this addon rewrites the Host HTTP header. I have no clue what you are trying to accomplish, but rewriting google to bing makes no sense.

That was just an example, like you did with "codefreak.net" --> "bloodisgood.net"

I give a try to this addon thinking that it does the following:
- some example server, like: example.com, using other ip, like 127.0.0.1 or localhost
but may not work this way I think

**Comment by RainOrigami** [comment]
if localhost is serving example.com then yes, you can rewrite localhost to example.com.

> That was just an example, like you did with "codefreak.net" --> "bloodisgood.net"

I was using codefreak.net and bloodisgood.net because codefreak.net is serving bloodisgood.net.

**Comment by serhumanos** [comment]
I did the following:
- in my localhost I serve example.com (in my apache virtual hosts) and create a simple page
- I add 127.0.0.1 in hosts file to test.. and it works
- I remove entry fron hosts file (to leave the original ip address of "example.com")
- with addon disabled.. loads example.com (the original one)
- with addon enabled and setted to example.com --> localhost.. it shows a 404 error
![imagen](https://user-images.githubusercontent.com/7744939/201538971-e06e381e-8f1a-4ca1-9a41-57d343af7907.png)

what I am doing bad?

**Comment by RainOrigami** [comment]
You're using it the wrong way around. If you want to access example.com on localhost then you have to enter localhost in `IP Address` and example.com as `Virtual Host`, then access localhost in your browser and apache will serve example.com.

Because the request will be made by the browser to the requested host, but the HTTP Host header will be overwritten, thus asking the target to serve a page for a different vhost.

What you did was to ask example.com, which is 93.184.216.34, to serve you a page for vhost "localhost", which is why they give you a 404, as example.com does not serve localhost.
